### PR TITLE
visual bug fix when status bar is visible.

### PR DESCRIPTION
**Pull request by osrufung**
in certain configuration, it makes a strange animation when root view is resized

### CODE REVIEW

**Comment by autresphere** [comment]
Hi, the actual code already takes care of the status bar visibility. When the status bar is visible, the frame starts at origin.y = 20 in https://github.com/autresphere/ASDepthModal/blob/master/ASDepthModal/ASDepthModalViewController.m#L122 and everything seem to be ok.
Can you give more details about your configuration for which you have this issue?

**Comment by osrufung** [comment]
not in my case. It starts in 0,0 with size 320,480.  My configuration is:

AppDelegate -> window setRootViewController: NavigationController with a Simple UIViewController with a .xib file and popupView embedded :s

**Comment by autresphere** [comment]
Can you send me a small Xcode project showing the issue?

**Comment by autresphere** [comment]
I've managed to recreate this behavior. It's now fixed in all cases (until you find a new case ;-), also taking care of possible orientation.

**Pull request closed without merging**
